version: '3'
services:
  mongodb-phonebook:
    container_name: mongodb-phonebook
    build: ./src/mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'root'
      MONGO_REPLICA_PORT: '27018'
      MONGO_REPLICA_HOST: 'localhost'
    ports:
      - '27018:27018' 
  nginx:
    container_name: nginx
    build: ./src/nginx
    restart: always    
  server:
    container_name: server
    build: .
    restart: always
    depends_on:
      - mongodb-phonebook
      - nginx
    ports:
      - "3000:3000"